In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("F://Electric_Vehicle_Purchases//Data//train.csv")
vechile_df = df.copy()

In [5]:
vechile_df.head()

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
0,0,66,92887.0,23.4,2,3,7,1.0,Male,Suburban,Sedan,Yes,No,Low,No
1,1,38,30000.0,5.0,1,2,2,4.0,Male,Rural,SUV,Yes,No,Low,No
2,2,26,94389.0,36.8,1,8,15,5.0,Female,Urban,Sedan,No,Yes,Low,Yes
3,3,66,73580.0,23.7,2,6,9,3.0,Male,Suburban,Hatchback,Yes,No,Low,No
4,4,54,57898.0,50.8,1,2,3,3.0,Male,Suburban,Hatchback,Yes,No,Low,No

In [6]:
vechile_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 668665 entries, 0 to 668664
Data columns (total 15 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           668665 non-null  int64
 1   Age                          668665 non-null  int64
 2   Annual_Income_USD            668665 non-null  float64
 3   Daily_Commute_km             668665 non-null  float64
 4   Number_of_Cars_Owned         668665 non-null  int64
 5   Charging_Stations_Near_Home  668665 non-null  int64
 6   Charging_Stations_Near_Work  668665 non-null  int64
 7   Environmental_Concern_Level  668665 non-null  float64
 8   Gender                       668665 non-null  str
 9   City_Type                    668665 non-null  str
 10  Current_Car_Type             668665 non-null  str
 11  Home_Charging_Possible       668665 non-null  str
 12  Subsidy_Available            668665 non-null  str
 13  Range_Anxiety_Level          668665 non-null  str
 14  Will_Buy_EV                  668665 non-null  str
dtypes: float64(3), int64(5), str(7)
memory usage: 76.5 MB

In [7]:
vechile_df.describe()

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level
count,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000
mean,334332.000000,47.039171,84769.266989,32.158298,1.712626,4.960408,7.176314,2.935477
std,193027.103211,12.875448,28648.029042,18.730474,0.729275,3.926843,5.186627,1.429119
min,0.000000,25.000000,30000.000000,5.000000,1.000000,0.000000,0.000000,1.000000
25%,167166.000000,36.000000,67376.000000,17.200000,1.000000,2.000000,3.000000,2.000000
50%,334332.000000,47.000000,84880.000000,33.600000,2.000000,4.000000,6.000000,3.000000
75%,501498.000000,58.000000,102753.000000,47.400000,2.000000,7.000000,10.000000,4.000000
max,668664.000000,69.000000,188549.000000,98.700000,4.000000,14.000000,19.000000,5.000000

In [10]:
import sweetviz as sv

In [ ]:
report = sv.analyze(vechile_df)
report.show_html("F://Electric_Vehicle_Purchases//data_report.html" , open_browser=False)

In [12]:
vechile_df.head()

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
0,0,66,92887.0,23.4,2,3,7,1.0,Male,Suburban,Sedan,Yes,No,Low,No
1,1,38,30000.0,5.0,1,2,2,4.0,Male,Rural,SUV,Yes,No,Low,No
2,2,26,94389.0,36.8,1,8,15,5.0,Female,Urban,Sedan,No,Yes,Low,Yes
3,3,66,73580.0,23.7,2,6,9,3.0,Male,Suburban,Hatchback,Yes,No,Low,No
4,4,54,57898.0,50.8,1,2,3,3.0,Male,Suburban,Hatchback,Yes,No,Low,No

In [15]:
vechile_df["Will_Buy_EV"] = vechile_df["Will_Buy_EV"].map({"No" : 0 , "Yes" : 1})
vechile_df["Subsidy_Available"] = vechile_df["Subsidy_Available"].map({"Yes" : 1 , "No" : 0})
vechile_df["Home_Charging_Possible"] = vechile_df["Home_Charging_Possible"].map({"Yes" : 1 , "No" : 0})

In [16]:
vechile_df

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
0,0,66,92887.0,23.4,2,3,7,1.0,Male,Suburban,Sedan,1,0,Low,0
1,1,38,30000.0,5.0,1,2,2,4.0,Male,Rural,SUV,1,0,Low,0
2,2,26,94389.0,36.8,1,8,15,5.0,Female,Urban,Sedan,0,1,Low,1
3,3,66,73580.0,23.7,2,6,9,3.0,Male,Suburban,Hatchback,1,0,Low,0
4,4,54,57898.0,50.8,1,2,3,3.0,Male,Suburban,Hatchback,1,0,Low,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668660,668660,30,71090.0,27.4,2,5,6,5.0,Male,Urban,Sedan,0,1,Medium,0
668661,668661,32,129990.0,5.0,2,5,4,1.0,Female,Suburban,SUV,1,1,Low,0
668662,668662,64,121791.0,24.2,1,5,6,1.0,Female,Suburban,Hatchback,1,1,Low,0
668663,668663,51,115923.0,43.7,2,0,0,1.0,Female,Rural,SUV,1,1,Low,0
668664,668664,54,68986.0,5.0,1,6,9,2.0,Male,Urban,Hatchback,0,1,Low,0

In [17]:
vechile_df = pd.get_dummies(
    vechile_df,
    columns=["Gender" , "Current_Car_Type"],
    drop_first= True
)