In [3]:
import pandas as pd

In [123]:
df = pd.read_csv("F://Electric_Vehicle_Purchases//Data//train.csv")
vechile_df = df.copy()

In [27]:
vechile_df.head()

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
0,0,66,92887.0,23.4,2,3,7,1.0,Male,Suburban,Sedan,Yes,No,Low,No
1,1,38,30000.0,5.0,1,2,2,4.0,Male,Rural,SUV,Yes,No,Low,No
2,2,26,94389.0,36.8,1,8,15,5.0,Female,Urban,Sedan,No,Yes,Low,Yes
3,3,66,73580.0,23.7,2,6,9,3.0,Male,Suburban,Hatchback,Yes,No,Low,No
4,4,54,57898.0,50.8,1,2,3,3.0,Male,Suburban,Hatchback,Yes,No,Low,No

In [6]:
vechile_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 668665 entries, 0 to 668664
Data columns (total 15 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           668665 non-null  int64
 1   Age                          668665 non-null  int64
 2   Annual_Income_USD            668665 non-null  float64
 3   Daily_Commute_km             668665 non-null  float64
 4   Number_of_Cars_Owned         668665 non-null  int64
 5   Charging_Stations_Near_Home  668665 non-null  int64
 6   Charging_Stations_Near_Work  668665 non-null  int64
 7   Environmental_Concern_Level  668665 non-null  float64
 8   Gender                       668665 non-null  str
 9   City_Type                    668665 non-null  str
 10  Current_Car_Type             668665 non-null  str
 11  Home_Charging_Possible       668665 non-null  str
 12  Subsidy_Available            668665 non-null  str
 13  Range_Anxiety_Level          668665 non-null  str
 14  Will_Buy_EV                  668665 non-null  str
dtypes: float64(3), int64(5), str(7)
memory usage: 76.5 MB

In [7]:
vechile_df.describe()

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level
count,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000
mean,334332.000000,47.039171,84769.266989,32.158298,1.712626,4.960408,7.176314,2.935477
std,193027.103211,12.875448,28648.029042,18.730474,0.729275,3.926843,5.186627,1.429119
min,0.000000,25.000000,30000.000000,5.000000,1.000000,0.000000,0.000000,1.000000
25%,167166.000000,36.000000,67376.000000,17.200000,1.000000,2.000000,3.000000,2.000000
50%,334332.000000,47.000000,84880.000000,33.600000,2.000000,4.000000,6.000000,3.000000
75%,501498.000000,58.000000,102753.000000,47.400000,2.000000,7.000000,10.000000,4.000000
max,668664.000000,69.000000,188549.000000,98.700000,4.000000,14.000000,19.000000,5.000000

In [10]:
import sweetviz as sv

In [ ]:
report = sv.analyze(vechile_df)
report.show_html("F://Electric_Vehicle_Purchases//data_report.html" , open_browser=False)

In [12]:
vechile_df.head()

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
0,0,66,92887.0,23.4,2,3,7,1.0,Male,Suburban,Sedan,Yes,No,Low,No
1,1,38,30000.0,5.0,1,2,2,4.0,Male,Rural,SUV,Yes,No,Low,No
2,2,26,94389.0,36.8,1,8,15,5.0,Female,Urban,Sedan,No,Yes,Low,Yes
3,3,66,73580.0,23.7,2,6,9,3.0,Male,Suburban,Hatchback,Yes,No,Low,No
4,4,54,57898.0,50.8,1,2,3,3.0,Male,Suburban,Hatchback,Yes,No,Low,No

In [28]:
vechile_df["Will_Buy_EV"] = vechile_df["Will_Buy_EV"].map({"No" : 0 , "Yes" : 1})
vechile_df["Subsidy_Available"] = vechile_df["Subsidy_Available"].map({"Yes" : 1 , "No" : 0})
vechile_df["Home_Charging_Possible"] = vechile_df["Home_Charging_Possible"].map({"Yes" : 1 , "No" : 0})

In [29]:
vechile_df

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
0,0,66,92887.0,23.4,2,3,7,1.0,Male,Suburban,Sedan,1,0,Low,0
1,1,38,30000.0,5.0,1,2,2,4.0,Male,Rural,SUV,1,0,Low,0
2,2,26,94389.0,36.8,1,8,15,5.0,Female,Urban,Sedan,0,1,Low,1
3,3,66,73580.0,23.7,2,6,9,3.0,Male,Suburban,Hatchback,1,0,Low,0
4,4,54,57898.0,50.8,1,2,3,3.0,Male,Suburban,Hatchback,1,0,Low,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668660,668660,30,71090.0,27.4,2,5,6,5.0,Male,Urban,Sedan,0,1,Medium,0
668661,668661,32,129990.0,5.0,2,5,4,1.0,Female,Suburban,SUV,1,1,Low,0
668662,668662,64,121791.0,24.2,1,5,6,1.0,Female,Suburban,Hatchback,1,1,Low,0
668663,668663,51,115923.0,43.7,2,0,0,1.0,Female,Rural,SUV,1,1,Low,0
668664,668664,54,68986.0,5.0,1,6,9,2.0,Male,Urban,Hatchback,0,1,Low,0

In [30]:
vechile_df

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
0,0,66,92887.0,23.4,2,3,7,1.0,Male,Suburban,Sedan,1,0,Low,0
1,1,38,30000.0,5.0,1,2,2,4.0,Male,Rural,SUV,1,0,Low,0
2,2,26,94389.0,36.8,1,8,15,5.0,Female,Urban,Sedan,0,1,Low,1
3,3,66,73580.0,23.7,2,6,9,3.0,Male,Suburban,Hatchback,1,0,Low,0
4,4,54,57898.0,50.8,1,2,3,3.0,Male,Suburban,Hatchback,1,0,Low,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668660,668660,30,71090.0,27.4,2,5,6,5.0,Male,Urban,Sedan,0,1,Medium,0
668661,668661,32,129990.0,5.0,2,5,4,1.0,Female,Suburban,SUV,1,1,Low,0
668662,668662,64,121791.0,24.2,1,5,6,1.0,Female,Suburban,Hatchback,1,1,Low,0
668663,668663,51,115923.0,43.7,2,0,0,1.0,Female,Rural,SUV,1,1,Low,0
668664,668664,54,68986.0,5.0,1,6,9,2.0,Male,Urban,Hatchback,0,1,Low,0

In [31]:
vechile_df = pd.get_dummies(
    vechile_df,
    columns=["Gender" , "Current_Car_Type" , "City_Type" , "Range_Anxiety_Level"],
    drop_first= True
)

In [32]:
vechile_df

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Home_Charging_Possible,Subsidy_Available,Will_Buy_EV,Gender_Male,Gender_Other,Current_Car_Type_SUV,Current_Car_Type_Sedan,Current_Car_Type_Truck,City_Type_Suburban,City_Type_Urban,Range_Anxiety_Level_Low,Range_Anxiety_Level_Medium
0,0,66,92887.0,23.4,2,3,7,1.0,1,0,0,True,False,False,True,False,True,False,True,False
1,1,38,30000.0,5.0,1,2,2,4.0,1,0,0,True,False,True,False,False,False,False,True,False
2,2,26,94389.0,36.8,1,8,15,5.0,0,1,1,False,False,False,True,False,False,True,True,False
3,3,66,73580.0,23.7,2,6,9,3.0,1,0,0,True,False,False,False,False,True,False,True,False
4,4,54,57898.0,50.8,1,2,3,3.0,1,0,0,True,False,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668660,668660,30,71090.0,27.4,2,5,6,5.0,0,1,0,True,False,False,True,False,False,True,False,True
668661,668661,32,129990.0,5.0,2,5,4,1.0,1,1,0,False,False,True,False,False,True,False,True,False
668662,668662,64,121791.0,24.2,1,5,6,1.0,1,1,0,False,False,False,False,False,True,False,True,False
668663,668663,51,115923.0,43.7,2,0,0,1.0,1,1,0,False,False,True,False,False,False,False,True,False
668664,668664,54,68986.0,5.0,1,6,9,2.0,0,1,0,True,False,False,False,False,False,True,True,False

In [33]:
corr_matrix = vechile_df.corr()
corr_matrix["Will_Buy_EV"].sort_values(ascending=False)

Will_Buy_EV                    1.000000
Environmental_Concern_Level    0.464079
Subsidy_Available              0.342382
Annual_Income_USD              0.225729
Range_Anxiety_Level_Low        0.115744
Home_Charging_Possible         0.083584
City_Type_Suburban             0.013026
Current_Car_Type_SUV           0.012697
Number_of_Cars_Owned           0.003896
id                            -0.000013
Gender_Other                  -0.000215
Current_Car_Type_Sedan        -0.006429
Gender_Male                   -0.006971
Age                           -0.007450
Current_Car_Type_Truck        -0.011987
Charging_Stations_Near_Work   -0.012229
Charging_Stations_Near_Home   -0.016353
City_Type_Urban               -0.031251
Daily_Commute_km              -0.045866
Range_Anxiety_Level_Medium    -0.112401
Name: Will_Buy_EV, dtype: float64

In [36]:
X = vechile_df.drop(columns=["Will_Buy_EV"])
y = vechile_df["Will_Buy_EV"]

In [35]:
from sklearn.model_selection import train_test_split

In [42]:
x_sample , _ , y_sample , _ = train_test_split(
    X , y ,
    train_size=0.15,
    stratify=y,
    random_state=42
)

In [43]:
x_sample.shape

(100299, 19)

In [44]:
from xgboost import XGBClassifier

In [45]:
model = XGBClassifier(
    objective='binary:logistic',
    eval_metric='auc',
    random_state=42
)

In [48]:
from sklearn.model_selection import StratifiedKFold , cross_val_score

In [51]:
cv = StratifiedKFold(n_splits=5 , shuffle=True , random_state=42)

scores = cross_val_score(
    model , x_sample , y_sample,
    cv = cv,
    scoring="roc_auc",
    n_jobs=2
)

In [52]:
print(f"AUC per fold: {scores}")
print(f"Mean AUC: {scores.mean():.4f} (+/- {scores.std():.4f})")

AUC per fold: [0.93806901 0.9340498  0.93719749 0.93430886 0.93867985]
Mean AUC: 0.9365 (+/- 0.0019)

In [56]:
model.fit(x_sample , y_sample)
pd.Series(model.feature_importances_, index=x_sample.columns).sort_values(ascending=False)

Subsidy_Available              0.706280
Environmental_Concern_Level    0.196301
Range_Anxiety_Level_Low        0.034911
Annual_Income_USD              0.011810
Home_Charging_Possible         0.004056
Daily_Commute_km               0.003850
Range_Anxiety_Level_Medium     0.003595
Age                            0.003528
Current_Car_Type_Truck         0.003513
City_Type_Suburban             0.003431
Number_of_Cars_Owned           0.003395
id                             0.003332
Charging_Stations_Near_Work    0.003312
Charging_Stations_Near_Home    0.003281
Gender_Male                    0.003258
Current_Car_Type_SUV           0.003214
City_Type_Urban                0.003170
Gender_Other                   0.003000
Current_Car_Type_Sedan         0.002764
dtype: float32

In [98]:
vechile_df

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
0,0,66,92887.0,23.4,2,3,7,1.0,Male,Suburban,Sedan,Yes,No,Low,No
1,1,38,30000.0,5.0,1,2,2,4.0,Male,Rural,SUV,Yes,No,Low,No
2,2,26,94389.0,36.8,1,8,15,5.0,Female,Urban,Sedan,No,Yes,Low,Yes
3,3,66,73580.0,23.7,2,6,9,3.0,Male,Suburban,Hatchback,Yes,No,Low,No
4,4,54,57898.0,50.8,1,2,3,3.0,Male,Suburban,Hatchback,Yes,No,Low,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668660,668660,30,71090.0,27.4,2,5,6,5.0,Male,Urban,Sedan,No,Yes,Medium,No
668661,668661,32,129990.0,5.0,2,5,4,1.0,Female,Suburban,SUV,Yes,Yes,Low,No
668662,668662,64,121791.0,24.2,1,5,6,1.0,Female,Suburban,Hatchback,Yes,Yes,Low,No
668663,668663,51,115923.0,43.7,2,0,0,1.0,Female,Rural,SUV,Yes,Yes,Low,No
668664,668664,54,68986.0,5.0,1,6,9,2.0,Male,Urban,Hatchback,No,Yes,Low,No

In [99]:
vechile_df["Will_Buy_EV"] = vechile_df["Will_Buy_EV"].map({"No" : 0 , "Yes" : 1})
vechile_df["Subsidy_Available"] = vechile_df["Subsidy_Available"].map({"Yes" : 1 , "No" : 0})
vechile_df["Home_Charging_Possible"] = vechile_df["Home_Charging_Possible"].map({"Yes" : 1 , "No" : 0})

In [100]:
vechile_df = vechile_df.drop(columns=["Gender" , "Current_Car_Type" , "City_Type"])

In [101]:
from sklearn.preprocessing import OrdinalEncoder

In [102]:
enc = OrdinalEncoder(categories=[["Low" , "Medium" , "High"]])
vechile_df["Range_Anxiety_Level"] = enc.fit_transform(vechile_df[["Range_Anxiety_Level"]])

In [103]:
vechile_df

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
0,0,66,92887.0,23.4,2,3,7,1.0,1,0,0.0,0
1,1,38,30000.0,5.0,1,2,2,4.0,1,0,0.0,0
2,2,26,94389.0,36.8,1,8,15,5.0,0,1,0.0,1
3,3,66,73580.0,23.7,2,6,9,3.0,1,0,0.0,0
4,4,54,57898.0,50.8,1,2,3,3.0,1,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
668660,668660,30,71090.0,27.4,2,5,6,5.0,0,1,1.0,0
668661,668661,32,129990.0,5.0,2,5,4,1.0,1,1,0.0,0
668662,668662,64,121791.0,24.2,1,5,6,1.0,1,1,0.0,0
668663,668663,51,115923.0,43.7,2,0,0,1.0,1,1,0.0,0
668664,668664,54,68986.0,5.0,1,6,9,2.0,0,1,0.0,0

In [104]:
vechile_df = vechile_df.drop(columns = ["id"])

In [105]:
X = vechile_df.drop(columns=["Will_Buy_EV"])
y = vechile_df["Will_Buy_EV"]

In [106]:
x_sample , _ , y_sample , _ = train_test_split(
    X , y ,
    train_size=0.15,
    stratify=y,
    random_state=42
)

In [107]:
cv = StratifiedKFold(n_splits=5 , shuffle=True , random_state=42)

scores = cross_val_score(
    model , x_sample , y_sample,
    cv = cv,
    scoring="roc_auc",
    n_jobs=2
)

In [108]:
print(f"AUC per fold: {scores}")
print(f"Mean AUC: {scores.mean():.4f} (+/- {scores.std():.4f})")

AUC per fold: [0.93839111 0.93568686 0.93845328 0.93569454 0.9389224 ]
Mean AUC: 0.9374 (+/- 0.0014)

In [109]:
model.fit(x_sample , y_sample)
pd.Series(model.feature_importances_, index=x_sample.columns).sort_values(ascending=False)

Subsidy_Available              0.760431
Environmental_Concern_Level    0.175197
Range_Anxiety_Level            0.032020
Annual_Income_USD              0.011659
Daily_Commute_km               0.003787
Home_Charging_Possible         0.003704
Age                            0.003440
Charging_Stations_Near_Work    0.003314
Number_of_Cars_Owned           0.003268
Charging_Stations_Near_Home    0.003178
dtype: float32

In [110]:
vechile_df.dtypes

Age                              int64
Annual_Income_USD              float64
Daily_Commute_km               float64
Number_of_Cars_Owned             int64
Charging_Stations_Near_Home      int64
Charging_Stations_Near_Work      int64
Environmental_Concern_Level    float64
Home_Charging_Possible           int64
Subsidy_Available                int64
Range_Anxiety_Level            float64
Will_Buy_EV                      int64
dtype: object

In [114]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [121]:
ord_pipeline = Pipeline(
    [
        ("Encoder" , OrdinalEncoder(categories= [["Low" , "Medium" , "High"]])),
        ("Scaler", StandardScaler())
    ]
)

In [120]:
numeric_pipeline = Pipeline(
    [
        ("Scaler" , StandardScaler())
    ]
)

In [119]:
preprocessor = ColumnTransformer(
    [
    ("categorical" , ord_pipeline , ["Range_Anxiety_Level"]),
    ("num" , numeric_pipeline , ["Age" , "Annual_Income_USD" , "Daily_Commute_km" , "Number_of_Cars_Owned" , "Charging_Stations_Near_Home" , "Charging_Stations_Near_Work" , "Environmental_Concern_Level" , "Home_Charging_Possible" , "Subsidy_Available"])
    ]
)

In [125]:
vechile_df

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
0,0,66,92887.0,23.4,2,3,7,1.0,Male,Suburban,Sedan,Yes,No,Low,No
1,1,38,30000.0,5.0,1,2,2,4.0,Male,Rural,SUV,Yes,No,Low,No
2,2,26,94389.0,36.8,1,8,15,5.0,Female,Urban,Sedan,No,Yes,Low,Yes
3,3,66,73580.0,23.7,2,6,9,3.0,Male,Suburban,Hatchback,Yes,No,Low,No
4,4,54,57898.0,50.8,1,2,3,3.0,Male,Suburban,Hatchback,Yes,No,Low,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668660,668660,30,71090.0,27.4,2,5,6,5.0,Male,Urban,Sedan,No,Yes,Medium,No
668661,668661,32,129990.0,5.0,2,5,4,1.0,Female,Suburban,SUV,Yes,Yes,Low,No
668662,668662,64,121791.0,24.2,1,5,6,1.0,Female,Suburban,Hatchback,Yes,Yes,Low,No
668663,668663,51,115923.0,43.7,2,0,0,1.0,Female,Rural,SUV,Yes,Yes,Low,No
668664,668664,54,68986.0,5.0,1,6,9,2.0,Male,Urban,Hatchback,No,Yes,Low,No

In [126]:
vechile_df["Will_Buy_EV"] = vechile_df["Will_Buy_EV"].map({"No" : 0 , "Yes" : 1})
vechile_df["Subsidy_Available"] = vechile_df["Subsidy_Available"].map({"Yes" : 1 , "No" : 0})
vechile_df["Home_Charging_Possible"] = vechile_df["Home_Charging_Possible"].map({"Yes" : 1 , "No" : 0})

In [127]:
X = vechile_df.drop(columns = ["id" , "Gender" , "City_Type" , "Will_Buy_EV" , "Current_Car_Type"])
y = vechile_df["Will_Buy_EV"]

In [132]:
X_sample , _ , y_sample , _ = train_test_split(
    X , y ,
    train_size=0.15,
    stratify=y,
    random_state=42
)

In [130]:
from sklearn.linear_model import LogisticRegression

In [157]:
logistic_pipeline = Pipeline(
    [
        ("preprocessing" , preprocessor),
        ("model" , LogisticRegression(C=1.93 , max_iter=1000) )
    ]
)

In [133]:
scores = cross_val_score(
    logistic_pipeline, X_sample, y_sample,
    cv=cv,
    scoring='roc_auc',
    n_jobs=2
)

print(f"AUC per fold: {scores}")
print(f"Mean AUC: {scores.mean():.4f} (+/- {scores.std():.4f})")

AUC per fold: [0.94006992 0.93615904 0.93881175 0.93700775 0.93875494]
Mean AUC: 0.9382 (+/- 0.0014)

In [134]:
from sklearn.svm import LinearSVC

In [135]:
Svc_pipeline = Pipeline(
    [
        ("preprocessing" , preprocessor),
        ("model" , LinearSVC(C=100 , random_state=42) )
    ]
)

In [136]:
scores = cross_val_score(
    Svc_pipeline, X_sample, y_sample,
    cv=cv,
    scoring='roc_auc',
    n_jobs=2
)

print(f"AUC per fold: {scores}")
print(f"Mean AUC: {scores.mean():.4f} (+/- {scores.std():.4f})")

AUC per fold: [0.94005977 0.93569581 0.93894401 0.93671335 0.93864397]
Mean AUC: 0.9380 (+/- 0.0016)

In [137]:
from sklearn.calibration import CalibratedClassifierCV
from sklearn.preprocessing import PolynomialFeatures

In [138]:
Svc_poly_pipeline = Pipeline(
    [
        ("preprocessing", preprocessor),
        ("PolynomialFeatures", PolynomialFeatures(degree=2)),
        ("model", CalibratedClassifierCV(
            LinearSVC(tol=0.0001, max_iter=5000, loss='squared_hinge', C=10, random_state=42),
            cv=3
        ))
    ]
)

In [139]:
scores = cross_val_score(
    Svc_poly_pipeline, X_sample, y_sample,
    cv=cv,
    scoring='roc_auc',
    n_jobs=2
)

print(f"AUC per fold: {scores}")
print(f"Mean AUC: {scores.mean():.4f} (+/- {scores.std():.4f})")

AUC per fold: [0.93831841 0.93427084 0.93721648 0.93406299 0.93740845]
Mean AUC: 0.9363 (+/- 0.0017)

In [140]:
from sklearn.tree import DecisionTreeClassifier

In [141]:
Tree_pipeline = Pipeline(
    [
        ("preprocessing" , preprocessor),
        ("model" , DecisionTreeClassifier(min_samples_split = 10, min_samples_leaf = 20, max_depth = 10, criterion = 'entropy' , random_state=42) )
    ]
)

In [142]:
scores = cross_val_score(
    Tree_pipeline, X_sample, y_sample,
    cv=cv,
    scoring='roc_auc',
    n_jobs=2
)

print(f"AUC per fold: {scores}")
print(f"Mean AUC: {scores.mean():.4f} (+/- {scores.std():.4f})")

AUC per fold: [0.9323299  0.93163362 0.92930101 0.9285035  0.93124793]
Mean AUC: 0.9306 (+/- 0.0015)

In [144]:
from sklearn.ensemble import RandomForestClassifier

In [145]:
forest_pipeline = Pipeline(
    [
        ("preprocessing" , preprocessor),
        ("model" ,  RandomForestClassifier(n_estimators = 500, min_samples_split = 20, min_samples_leaf = 2, max_features = 'log2', max_depth = 20, criterion =  'entropy', random_state=42) )
    ]
)

In [146]:
scores = cross_val_score(
    forest_pipeline, X_sample, y_sample,
    cv=cv,
    scoring='roc_auc',
    n_jobs=2
)

print(f"AUC per fold: {scores}")
print(f"Mean AUC: {scores.mean():.4f} (+/- {scores.std():.4f})")

AUC per fold: [0.93882448 0.93638315 0.93871956 0.93670316 0.9393934 ]
Mean AUC: 0.9380 (+/- 0.0012)

In [152]:
boosted_forest_pipeline = Pipeline(
    [
        ("Preprocessing" , preprocessor),
        ("Model" , XGBClassifier(subsample = 0.7, n_estimators = 200, min_child_weight = 5, max_depth = 4, learning_rate = 0.1, gamma = 1, colsample_bytree = 0.7 ,objective='binary:logistic', eval_metric='auc', random_state=42))
    ]
)

In [153]:
scores = cross_val_score(
    boosted_forest_pipeline, X_sample, y_sample,
    cv=cv,
    scoring='roc_auc',
    n_jobs=2
)

print(f"AUC per fold: {scores}")
print(f"Mean AUC: {scores.mean():.4f} (+/- {scores.std():.4f})")

AUC per fold: [0.94202851 0.93878136 0.94185834 0.93915161 0.94233634]
Mean AUC: 0.9408 (+/- 0.0015)

In [149]:
from sklearn.model_selection import RandomizedSearchCV

In [150]:
param_dist = {
    "Model__n_estimators": [100, 150, 200],
    "Model__max_depth": [2, 3, 4, 5],       
    "Model__learning_rate": [0.01, 0.05, 0.1],
    "Model__subsample": [0.6, 0.7, 0.8],
    "Model__colsample_bytree": [0.6, 0.7, 0.8],
    "Model__gamma": [0.5, 1, 2, 5],           
    "Model__min_child_weight": [5, 7, 10, 15] 
}

In [151]:
random_boosted_search = RandomizedSearchCV(
    boosted_forest_pipeline,
    param_distributions=param_dist,
    n_iter=75,
    cv=5,
    scoring='roc_auc',
    random_state=42,
    n_jobs=2
)

random_boosted_search.fit( X_sample, y_sample)
print(random_boosted_search.best_params_)
print(random_boosted_search.best_score_)

{'Model__subsample': 0.7, 'Model__n_estimators': 200, 'Model__min_child_weight': 5, 'Model__max_depth': 4, 'Model__learning_rate': 0.1, 'Model__gamma': 1, 'Model__colsample_bytree': 0.7}
0.9407614010998125

In [155]:
param_grid = {
    "model__C": [0.001, 0.01, 0.1, 1, 1.93, 10, 100],
    "model__penalty": ["l1", "l2", "elasticnet", None],
    "model__solver": ["saga"],
    "model__class_weight": [None, "balanced"],
}

In [156]:
random_logistic_search = RandomizedSearchCV(
    logistic_pipeline,
    param_distributions=param_grid,
    n_iter=75,
    cv=5,
    scoring='roc_auc',
    random_state=42,
    n_jobs=2
)

random_logistic_search.fit( X_sample, y_sample)
print(random_logistic_search.best_params_)
print(random_logistic_search.best_score_)

f:\Electric_Vehicle_Purchases\.venv\Lib\site-packages\sklearn\model_selection\_search.py:326: UserWarning: The total space of parameters 56 is smaller than n_iter=75. Running 56 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
f:\Electric_Vehicle_Purchases\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
f:\Electric_Vehicle_Purchases\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1443: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(

{'model__solver': 'saga', 'model__penalty': None, 'model__class_weight': 'balanced', 'model__C': 10}
0.9381639915133828